-- ============================================================
-- 141 — شكل القاعدة كامل (schema)  (قراءة فقط)
-- ============================================================
--
-- ✅ **قراءة فقط.** مفيش ولا تعديل ولا إنشاء.
--
-- ── ليه الملف ده ────────────────────────────────────────────
--
-- ملفات SQL في المشروع **مش هي الحقيقة كاملة**: جداول كتير اتعملت من
-- لوحة Supabase أو من برّه الملفات (زي جداول صندوق الرحلة — تشخيص 139).
-- فالنسخة الوحيدة الصحيحة هي اللي في القاعدة نفسها، والملف ده بيطبعها.
--
-- ── بيطبع إيه ───────────────────────────────────────────────
--
-- كل حاجة في مخطط `public` (جداول الموقع)، كتعريف SQL جاهز:
--
--   ٠. ملخص بالأعداد — عشان تتأكد إن مفيش حاجة ناقصة
--   ١. الإضافات (extensions)
--   ٢. الأنواع المعرّفة (enum)
--   ٣. الجداول: الأعمدة، الأنواع، الافتراضي، الإلزامي، المفاتيح والروابط
--      والقيود، وهل الحماية (RLS) مفعّلة
--   ٤. الفهارس (اللي مش جاية من مفتاح أو قيد)
--   ٥. العروض (views)
--   ٦. الدوال كاملة بنصّها
--   ٧. المحفّزات (triggers)
--   ٨. سياسات الصلاحيات (RLS policies)
--   ٩. مين يقدر ينفّذ كل دالة
--
-- ⚠️ **مش بيطبع البيانات نفسها** — ولا صف واحد من أي جدول. الشكل بس.
-- ⚠️ ومش بيطبع مخططات Supabase الداخلية (`auth` و`storage`) — دي بتاعة
--    Supabase ومش بنعدّل فيها.
--
-- ── إزاي تاخد النتيجة ───────────────────────────────────────
--
-- شغّله في SQL Editor، وبعدين من فوق جدول النتيجة:
--   Export ← Download CSV
-- الملف ده هو «آخر schema». ابعته لي أو حطّه في فولدر المشروع.
-- ============================================================

WITH
tbl AS (
  SELECT c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c
  WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')
),
cols AS (
  SELECT a.attrelid,
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                            WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END
      || CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
              WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
              ELSE '' END
      || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
      E',\n' ORDER BY a.attnum) AS body
  FROM pg_attribute a
  JOIN tbl t ON t.oid = a.attrelid
  LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  WHERE a.attnum > 0 AND NOT a.attisdropped
  GROUP BY a.attrelid
),
cons AS (
  SELECT conrelid,
    string_agg('  CONSTRAINT ' || quote_ident(conname) || ' ' || pg_get_constraintdef(oid), E',\n'
      ORDER BY CASE contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'f' THEN 3 ELSE 4 END, conname) AS body
  FROM pg_constraint
  WHERE conrelid IN (SELECT oid FROM tbl) AND contype IN ('p', 'u', 'f', 'c', 'x')
  GROUP BY conrelid
),
fns AS (
  SELECT p.oid, p.proname, p.prokind, p.proacl,
    p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS sig
  FROM pg_proc p
  WHERE p.pronamespace = 'public'::regnamespace
    AND p.prokind IN ('f', 'p')
    -- دوال الإضافات مش بتاعتنا
    AND NOT EXISTS (SELECT 1 FROM pg_depend dp WHERE dp.objid = p.oid AND dp.deptype = 'e')
),
trg AS (
  SELECT t.oid, c.relname, t.tgname
  FROM pg_trigger t JOIN tbl c ON c.oid = t.tgrelid
  WHERE NOT t.tgisinternal
),
idx AS (
  SELECT i.indexrelid, ic.relname AS idxname, t.relname AS tblname
  FROM pg_index i
  JOIN tbl t ON t.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.indexrelid)
),
vw AS (
  SELECT c.oid, c.relname, c.relkind
  FROM pg_class c
  WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('v', 'm')
)

SELECT "ت", "القسم", "الاسم", "التعريف" FROM (

  -- ٠) ملخص
  SELECT 0 AS "ت", '0. ملخص' AS "القسم", 'الأعداد' AS "الاسم",
    'جداول: ' || (SELECT count(*) FROM tbl)
    || ' · بحماية RLS: ' || (SELECT count(*) FROM tbl WHERE relrowsecurity)
    || ' · فهارس إضافية: ' || (SELECT count(*) FROM idx)
    || ' · عروض: ' || (SELECT count(*) FROM vw)
    || ' · دوال: ' || (SELECT count(*) FROM fns)
    || ' · محفّزات: ' || (SELECT count(*) FROM trg)
    || ' · سياسات: ' || (SELECT count(*) FROM pg_policies WHERE schemaname = 'public')
    || ' · أنواع enum: ' || (SELECT count(*) FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typtype = 'e')
    || ' · وقت الطباعة: ' || to_char(now() AT TIME ZONE 'Africa/Cairo', 'YYYY-MM-DD HH24:MI') || ' (القاهرة)'
    AS "التعريف"

  UNION ALL
  -- ١) الإضافات
  SELECT 1, '1. إضافات', e.extname,
    'CREATE EXTENSION IF NOT EXISTS ' || quote_ident(e.extname) || ' WITH SCHEMA ' || quote_ident(n.nspname)
    || ';  -- v' || e.extversion
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname <> 'plpgsql'

  UNION ALL
  -- ٢) أنواع enum
  SELECT 2, '2. أنواع', t.typname,
    'CREATE TYPE public.' || quote_ident(t.typname) || ' AS ENUM ('
    || (SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid = t.oid)
    || ');'
  FROM pg_type t
  WHERE t.typnamespace = 'public'::regnamespace AND t.typtype = 'e'

  UNION ALL
  -- ٣) الجداول
  SELECT 3, '3. جداول', t.relname,
    'CREATE TABLE public.' || quote_ident(t.relname) || E' (\n'
    || coalesce(c.body, '')
    || CASE WHEN k.body IS NOT NULL THEN E',\n' || k.body ELSE '' END
    || E'\n);'
    || CASE WHEN t.relrowsecurity THEN E'\nALTER TABLE public.' || quote_ident(t.relname) || ' ENABLE ROW LEVEL SECURITY;'
            ELSE E'\n-- ⚠️ الحماية (RLS) مش مفعّلة على الجدول ده' END
    || CASE WHEN t.relforcerowsecurity THEN E'\nALTER TABLE public.' || quote_ident(t.relname) || ' FORCE ROW LEVEL SECURITY;' ELSE '' END
    || coalesce(E'\nCOMMENT ON TABLE public.' || quote_ident(t.relname) || ' IS ' || quote_literal(obj_description(t.oid, 'pg_class')) || ';', '')
  FROM tbl t
  LEFT JOIN cols c ON c.attrelid = t.oid
  LEFT JOIN cons k ON k.conrelid = t.oid

  UNION ALL
  -- ٤) الفهارس
  SELECT 4, '4. فهارس', x.tblname || ' · ' || x.idxname, pg_get_indexdef(x.indexrelid) || ';'
  FROM idx x

  UNION ALL
  -- ٥) العروض
  SELECT 5, '5. عروض', v.relname,
    CASE v.relkind WHEN 'm' THEN 'CREATE MATERIALIZED VIEW ' ELSE 'CREATE OR REPLACE VIEW ' END
    || 'public.' || quote_ident(v.relname) || E' AS\n' || pg_get_viewdef(v.oid, true)
  FROM vw v

  UNION ALL
  -- ٦) الدوال
  SELECT 6, '6. دوال', f.sig, pg_get_functiondef(f.oid) || ';'
  FROM fns f

  UNION ALL
  -- ٧) المحفّزات
  SELECT 7, '7. محفّزات', g.relname || ' · ' || g.tgname, pg_get_triggerdef(g.oid, true) || ';'
  FROM trg g

  UNION ALL
  -- ٨) سياسات الصلاحيات
  SELECT 8, '8. سياسات', p.tablename || ' · ' || p.policyname,
    'CREATE POLICY ' || quote_ident(p.policyname) || ' ON public.' || quote_ident(p.tablename)
    || ' AS ' || p.permissive || ' FOR ' || p.cmd
    || ' TO ' || array_to_string(p.roles, ', ')
    || coalesce(E'\n  USING (' || p.qual || ')', '')
    || coalesce(E'\n  WITH CHECK (' || p.with_check || ')', '')
    || ';'
  FROM pg_policies p
  WHERE p.schemaname = 'public'

  UNION ALL
  -- ٩) مين ينفّذ كل دالة (فاضي = الافتراضي: الكل، بما فيهم الزائر)
  SELECT 9, '9. صلاحية تنفيذ الدوال', f.sig,
    CASE WHEN f.proacl IS NULL THEN '(الافتراضي — public: أي حد، بما فيهم الزائر)'
         ELSE array_to_string(f.proacl, ', ') END
  FROM fns f

) x
ORDER BY "ت", "الاسم";
